version: "3.9"
services:
  agent-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      LIVEKIT_URL: ${LIVEKIT_URL}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TURN_WEBHOOK_URL: ${TURN_WEBHOOK}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE: ${SUPABASE_SERVICE_ROLE}
    restart: unless-stopped
